# (c) The Exploration Company
#
# Nix expression that sets up lauterbach t32 in the nix environment
# The following instructions provide a set of commands that were used
# to analyze the dependencies in case this expression may need to be updated
# in the future.
#
# Direct runtime dependencies on the main .t32marm-wrapped binary
# ```
# readelf -d files/bin/pc_linux64/t32marm | grep NEEDED
# ```
#
# Direct runtime dependencies on the qt6 shim t32screenqt6.so
# ```
# readelf -d files/bin/pc_linux64/t32screenqt6.so | grep NEEDED
# ```
#
# Transitive misses detected trough autoPatchelfHook
# ```
# nix build .#trace32 2>&1 | grep -E "not satisfied|dependency .* not found"
# ```
# dlopen candidates from strings grepped the main elf
# ```
# strings files/bin/pc_linux64/.t32marm-wrapped | grep -E '\.so(\.[0-9]+)?$'
# ```


{ stdenv
, lib
, autoPatchelfHook
, makeWrapper
, glibc
, gcc-unwrapped
, openssl
, curl
, brotli
, libkrb5
, libssh2
, zstd
, libunistring
, libidn2
, libpsl
, nghttp2
, libnghttp3 ? null
, ngtcp2 ? null
, libuuid
, keyutils
, e2fsprogs
, freetype
, fontconfig
, harfbuzz
, icu
, libpng
, xorg
, libxkbcommon
, dbus
, glib
, expat
, systemdLibs
, liburing
, libGL
, libglvnd
, qt6
, bzip2
, zlib
, libb2
, double-conversion
, pcre2
, md4c
, graphite2
, src
}:

stdenv.mkDerivation {
  pname = "trace32";
  version = "R.2026.02.000190766";
  inherit src;

  nativeBuildInputs = [ autoPatchelfHook makeWrapper ];

  buildInputs = [
    glibc
    gcc-unwrapped.lib
    openssl
    curl
    brotli
    libkrb5
    libssh2
    zstd
    libunistring
    libidn2
    libpsl
    nghttp2
    libuuid
    keyutils
    e2fsprogs

    qt6.qtbase
    qt6.qtsvg
    freetype
    fontconfig
    harfbuzz
    icu
    libpng
    libxkbcommon
    dbus
    glib
    expat
    systemdLibs
    liburing
    libGL
    libglvnd
    bzip2
    zlib
    libb2
    double-conversion
    pcre2
    md4c
    graphite2

    xorg.libX11
    xorg.libXext
    xorg.libXau
    xorg.libXdmcp
    xorg.libxcb
    xorg.libSM
    xorg.libICE
  ] ++ lib.optional (libnghttp3 != null) libnghttp3
    ++ lib.optional (ngtcp2 != null) ngtcp2;

  dontUnpack = true;
  dontConfigure = true;
  dontBuild = true;
  dontWrapQtApps = true;

  installPhase = ''
    runHook preInstall

    mkdir -p "$out"

    # Dependencies for the linux-x64 install.
    # Excludes mac/win/aarch64 binaries.
    cp -r "$src/files/bin/pc_linux64" "$out/bin/"
    cp -r "$src/files/demo"     "$out/demo"
    cp -r "$src/files/licenses" "$out/licenses"
    cp -r "$src/files/fonts"    "$out/fonts"
    cp -r "$src/files/pdf"      "$out/pdf"

    # Front-end configuration blobs and the autostart script.
    for f in "$src"/files/*.t32 "$src"/files/autostart.cmm; do
      cp "$f" "$out/"
    done

    chmod -R u+w "$out"

    # Intel Trace Hub x64 demo binaries have been removed because they
    # link against packages that nixpkgs does not carry.
    rm -rf "$out/demo/x64/ith"

    # writable tmp dir used by t32 for state.
    mkdir -p "$out/tmp"
    chmod 0777 "$out/tmp"

    # udev rules for the LB debug hardware.
    mkdir -p "$out/lib/udev/rules.d"
    cp "$src/files/bin/pc_linux64/udev.conf/kernel_starting_4.14/10-lauterbach.rules" \
       "$out/lib/udev/rules.d/"
    cp "$src/files/bin/pc_linux64/udev.conf/kernel_starting_4.14/10-lauterbach_target.rules" \
       "$out/lib/udev/rules.d/"

    # Default config so `t32marm` works if launched without -c.
    cat > "$out/config.t32" <<CONFIG
    ; Auto-generated by tools/t32/trace32.nix
    OS=
    SYS=$out
    TMP=$out/tmp

    PBI=
    USB
    CONNECTIONMODE=AUTOCONNECT
    CONFIG

    runHook postInstall
  '';

  postFixup = ''
    for bin in "$out/bin"/t32m*; do
      case "$bin" in *.so|*.so.*|*/t32marm64) continue;; esac
      [ -x "$bin" ] || continue
      wrapProgram "$bin" \
        --set-default T32SCREENSO t32screenqt6.so \
        --prefix QT_PLUGIN_PATH : "${qt6.qtbase}/lib/qt-6/plugins" \
        --prefix QT_QPA_PLATFORM_PLUGIN_PATH : "${qt6.qtbase}/lib/qt-6/plugins/platforms"
    done
  '';

  autoPatchelfIgnoreMissingDeps = [
    "t32cadi.so.1"
    "t32caditrace.so"
    "t32cevadislink.so"
    "t32iris.so"
    "t32screenqt5.so"
    "t32screenqt6.so"
    "t32_tas_api.so"
    "libusb-1.0.so"
    "bmcmci.so"
    "hostmci.so"

    "libXxf86vm.so.1"
    "libgtk-3.so.0"
    "libgdk-3.so.0"
    "libatk-1.0.so.0"
    "libpangocairo-1.0.so.0"
    "libgdk_pixbuf-2.0.so.0"
    "libcairo-gobject.so.2"
    "libcairo.so.2"
    "libpangoft2-1.0.so.0"
    "libpango-1.0.so.0"

    "libQt5PrintSupport.so.5"
    "libQt5Svg.so.5"
    "libQt5Widgets.so.5"
    "libQt5Gui.so.5"
    "libQt5Core.so.5"
  ];

  meta = with lib; {
    description = "Lauterbach TRACE32 debugger";
    homepage = "https://www.lauterbach.com";
    license = licenses.unfree;
    platforms = [ "x86_64-linux" ];
    mainProgram = "t32marm";
  };
}
